In [2]:
import numpy as np
from src.calibration import ActuationNet

In [3]:
model = ActuationNet.load_from('notebooks/training/octomag_params/ActuationNet_100_512x512x512.pt')

In [4]:
currents = np.array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]) # A
pos = np.array([0.0, 0.0, 0.0]) # m

In [5]:
model.get_field_and_grad9(pos=pos, currents=currents) # mT

(array([ 2.0885656 , -0.13154128, -1.6924744 ], dtype=float32),
 array([[  8.68168   ,   5.117141  , -50.151268  ],
        [ 10.439264  , -38.024582  ,   0.81236476],
        [-53.236507  ,   0.88716626,  27.648832  ]], dtype=float32))

In [7]:
model.get_field_and_grad5(pos=pos, currents=currents) # mT

(array([ 2.0885656 , -0.13154128, -1.6924744 ], dtype=float32),
 array([  8.68168   ,   5.117141  , -50.151268  , -38.024582  ,
          0.81236476], dtype=float32))

In [8]:
model.get_field(pos=pos, currents=currents) # mT

array([ 2.0885656 , -0.13154128, -1.6924744 ], dtype=float32)

In [9]:
model.get_grad5(pos=pos, currents=currents) # mT

array([  8.68168   ,   5.117141  , -50.151268  , -38.024582  ,
         0.81236476], dtype=float32)